In [1]:
with open("../ShiftMLv1_datasets/CSD-2k/gipaw/ABEWAG.nmr.out") as file:
    lines = file.readlines()

In [14]:
import numpy as np

In [19]:

#get macroscopic contribution



In [ ]:
#get structure

In [53]:
iso, tens = get_contributions(lines, "Total sigma: ", True)

In [156]:
def get_macroscopic_tensor(lines):
    """retrieves the macroscopic contribution iso and tensor from a GIPAW FILE as line-list
    """
    for n,line in enumerate(lines):
        if  "Macroscopic shape contribution in ppm:" in line:
            macroscopic_iso = float(line.split()[-1])
            macroscopic_tensor = lines[n+1:n+4]
            macroscopic_tensor = [ column.rstrip("\n").split() for column in macroscopic_tensor]
            macroscopic_tensor = np.array(macroscopic_tensor,dtype=float)
    
    return macroscopic_iso, macroscopic_tensor

def get_contributions(lines,propstring,istens):
    """gets contribution iso and tensorial from GIPAW FILE
       istens option is for "core" contirbution which has no tensor written
       and will be added on diagonal
    """
    
    props_iso = []
    props_tensor = []
    
    for n, line in enumerate(lines):
        
        if propstring in line:
            iso = float(line.rstrip("\n").split()[-1])
            
            if istens is True:
                tensor = [ column.rstrip("\n").split() for column in lines[n+1:n+4]]
                tensor = np.array(tensor,dtype=float)
            
            else:
                tensor = np.eye(3)
                tensor *= iso
        
            props_iso.append(iso)
            props_tensor.append(tensor)
    
    return np.array(props_iso).reshape(-1,1), np.array(props_tensor)

def get_nmr_contributions(lines):
    """gets the individual_contributions of GIPAW shift calculations
    """

    tot_iso = {}
    tot_tens = {}

    iso_makro, tens_makro = get_macroscopic_tensor(lines)
    
    prop_identifiers = {"core sigma:":"core_sigma","para_oo sigma:":"para_oo_sigma",\
                        "para_lq sigma:":"para_lq_sigma","para sigma:":"para_sigma",\
                        "dia sigma:":"dia_sigma","bare sigma:":"bare_sigma"}

    for propstring in ["core sigma:", "para_oo sigma:", "para_lq sigma:", "para sigma:", "dia sigma:", "bare sigma:"]:

        if propstring == "core sigma:":
            iso, tens = get_contributions(lines, propstring, False)

        else:
            iso, tens = get_contributions(lines, propstring, True)
        
        identifier = prop_identifiers[propstring]
        tot_iso[identifier+"_iso"] = iso 
        tot_tens[identifier+"_tensor"] = tens
    
    tot_iso["shape_contribution_iso"] = iso_makro
    tot_tens["shape_contribution_iso"] = tens_makro

    return tot_iso, tot_tens


In [162]:
a = get_nmr_contributions(lines)

In [ ]:
tot_iso = np.concatenate(tot_iso,axis=1)
    tot_tens = np.stack(tot_tens,axis=3)#,axis=1)

    final_iso, final_tens = get_contributions(lines, "Total sigma:",True)

    final_iso_contrib = np.sum(tot_iso,axis=1).reshape(-1,1) + iso_makro
    final_tens_contrib = np.sum(tot_tens,axis=3) + tens_makro

In [ ]:
def 

In [135]:
final_iso.shape

(72, 1)

In [136]:
final_iso_contrib.shape

(72, 1)

In [146]:
np.allclose(final_iso,final_iso_contrib,atol=0.01)

True

In [149]:
np.allclose(final_tens,final_tens_contrib,atol=0.001)

False

In [126]:
final_iso

array([[301.62],
       [301.61],
       [301.61],
       [301.62],
       [301.62],
       [301.61],
       [301.61],
       [301.62],
       [107.02],
       [107.02],
       [107.02],
       [107.02],
       [107.02],
       [107.02],
       [107.02],
       [107.02],
       [107.73],
       [107.74],
       [107.74],
       [107.73],
       [107.73],
       [107.74],
       [107.74],
       [107.73],
       [ 26.96],
       [ 26.96],
       [ 26.96],
       [ 26.96],
       [ 26.96],
       [ 26.96],
       [ 26.96],
       [ 26.96],
       [ 27.03],
       [ 27.03],
       [ 27.03],
       [ 27.03],
       [ 27.03],
       [ 27.03],
       [ 27.03],
       [ 27.03],
       [ 26.91],
       [ 26.91],
       [ 26.91],
       [ 26.91],
       [ 26.91],
       [ 26.91],
       [ 26.91],
       [ 26.91],
       [ 27.04],
       [ 27.04],
       [ 27.04],
       [ 27.04],
       [ 27.04],
       [ 27.04],
       [ 27.04],
       [ 27.04],
       [ 26.76],
       [ 26.76],
       [ 26.76

In [119]:
final_tens.shape

(72, 1)

In [114]:
tot_tens.shape

(72, 3, 3, 5)

In [116]:
np.sum(tot_tens,axis=3).shape

(72, 3, 3)

In [29]:

        print(iso)
        print(tensor)

17.65
[[17.6301  0.7178 -0.7659]
 [ 0.7178 17.6373  0.0662]
 [-0.7659  0.0662 17.6794]]
17.65
[[17.637  -0.7178 -0.0658]
 [-0.7178 17.6292 -0.7661]
 [-0.0658 -0.7661 17.6797]]
17.65
[[17.637  -0.7178  0.0658]
 [-0.7178 17.6292  0.7661]
 [ 0.0658  0.7661 17.6797]]
17.65
[[17.6301  0.7178  0.7659]
 [ 0.7178 17.6373 -0.0662]
 [ 0.7659 -0.0662 17.6794]]
17.65
[[17.6301  0.7178 -0.7659]
 [ 0.7178 17.6373  0.0662]
 [-0.7659  0.0662 17.6794]]
17.65
[[17.637  -0.7178 -0.0658]
 [-0.7178 17.6292 -0.7661]
 [-0.0658 -0.7661 17.6797]]
17.65
[[17.637  -0.7178  0.0658]
 [-0.7178 17.6292  0.7661]
 [ 0.0658  0.7661 17.6797]]
17.65
[[17.6301  0.7178  0.7659]
 [ 0.7178 17.6373 -0.0662]
 [ 0.7659 -0.0662 17.6794]]
4.18
[[ 4.1834 -0.0092 -0.149 ]
 [-0.0092  4.053   0.0071]
 [-0.149   0.0071  4.304 ]]
4.18
[[ 4.0529  0.0092 -0.0071]
 [ 0.0092  4.1833 -0.1491]
 [-0.0071 -0.1491  4.304 ]]
4.18
[[4.0529 0.0092 0.0071]
 [0.0092 4.1833 0.1491]
 [0.0071 0.1491 4.304 ]]
4.18
[[ 4.1834 -0.0092  0.149 ]
 [-0.0092  4

In [ ]:
macroscopic_iso = float(line.split()[-1])
            macroscopic_tensor = lines[n+1:n+4]
            macroscopic_tensor = [ column.rstrip("\n").split() for column in macroscopic_tensor]
            macroscopic_tensor = np.array(macroscopic_tensor,dtype=float)

In [ ]:
 iso_contribs = {"core_sigma_iso"}
    tensor_contribs = {"core_sigma_tens"}
    

In [21]:
get_macroscopic_tensor(lines)

(4.99,
 array([[5.0248, 0.    , 0.    ],
        [0.    , 5.0229, 0.    ],
        [0.    , 0.    , 4.9349]]))

In [ ]:
#core sigma: para_oo sigma: para sigma: dia sigma: bare sigma: Total sigma: 